### PR TITLE
Add SwiftPM support

### PR DESCRIPTION
**Pull request by ryanrhee**
Support for the swift package manager

### CODE REVIEW

**Comment by ryanrhee** [comment]
never mind, probably want a swift-y interface instead.

**Comment by ncreated** [comment]
@ryanrhee I'm not so sure about closing this PR. Neither `opentracing-swift` nor `opentracing-objc` provides OT APIs for Swift tracers that expose `@objc` APIs, no?

**Comment by ryanrhee** [comment]
you could write you own interop layer if you need `@objc`, right?

**Comment by ncreated** [comment]
> you could write you own interop layer if you need @objc, right?

Yes, that would be totally fine for the implementation. But to allow users use it with `Global.sharedTracer`, we'd have to annotate things in [`opentracing-swift`](https://github.com/opentracing/opentracing-swift) with `@objc`, no?

**Comment by ryanrhee** [comment]
if you need to use objc then why not `opentracing-objc`? and, if your codebase is in a mix and you need to use both, you could pick one and write a wrapper around it in the other language.

in general, the frameworks should support one language, and people in a transitionary state should use language wrappers.

**Comment by ncreated** [comment]
> if you need to use objc then why not opentracing-objc? and, if your codebase is in a mix and you need to use both, you could pick one and write a wrapper around it in the other language.
> in general, the frameworks should support one language, and people in a transitionary state should use language wrappers.

That's exactly my strategy - create Swift tracer and add Obj-C wrapper. I want my Swift tracer to conform to `opentracing-swift` and my Obj-C wrapper to conform to `opentracing-objc`.

Paraphrasing my point on SPM support for `opentracing-objc`, let me quote [this part of SPM doc](https://developer.apple.com/documentation/swift_packages):

> Swift packages are reusable components of Swift, Objective-C, Objective-C++, C, or C++ code that developers can use in their projects.

So, SPM is a valid dependency manager for Objective-C code, and what I ask for is to enable it for `opentracing-objc`. This way, people will be able to link my Obj-C tracer through SPM.

**Comment by ryanrhee** [comment]
I see. You’re welcome to add swiftpm support in a PR if you want, as long as it doesn’t remove the existing cocoapod functionality.

**Pull request closed without merging**
